Fix Twitter Card Image
katherinepeterson/readme.so pull request #24
Opened 2021-04-11 19:30 UTC by rohitjmathew

This PR adds a resized image which should be able to fit and scale better on twitter cards. Related code changes to be able to enable the above fix. 

This PR closes #23

2021-04-11 20:19 UTC, rohitjmathew commented
@katherinepeterson I have fixed the issue. You can test the card [here](https://cards-dev.twitter.com/) with the latest preview deployed. You can go ahead and review and merge it

2021-04-11 21:55 UTC, katherinepeterson requested changes
Thanks, the card looks great! Do you mind pulling the latest and resolving the conflicts so I can merge?

2021-04-11 22:24 UTC, rohitjmathew commented
> Thanks, the card looks great! Do you mind pulling the latest and resolving the conflicts so I can merge?

@katherinepeterson conflicts resolved

2021-04-12 05:44 UTC, katherinepeterson approved these changes

2021-04-12 05:45 UTC, merged